Repository IT-Minds-opensource/ts-array-ext, pull requests merged in 2020-10, with the labels that each got.

#3 Version/v1.1.0
  .gitignore
  .npmignore
  package-lock.json
  package.json
  src/index.ts
  src/types.ts
  tests/index.test.ts
  tests/test.data.json
  tsconfig.json
Labels: enhancement

#5 Base type and implementation of unionSplit
  src/index.ts
  src/types.ts
  tests/index.test.ts
Labels: enhancement, good first issue

#7 Find and replace now using a function as accepted replacer. Resolves #6
  src/customErrors.ts
  src/index.ts
  src/typeGuards.ts
  src/types.ts
  tests/index.test.ts
  tests/testData.ts
Labels: enhancement, good first issue

#8 Chore/Documentation overhaul
  .editorconfig
  .eslintignore
  .eslintrc.js
  .github/workflows/npm-publish.yml
  .prettierignore
  .prettierrc
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  src/customErrors.ts
  src/index.ts
  src/types.ts
  tests/index.test.ts
  tsconfig.json
Labels: documentation, help wanted

#19 Chore/14 - Move from Mocha to Jest
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  tests/index.test.ts
  tests/test.data.json
Labels: hacktoberfest-accepted

#15 Feature Distinct
  README.md
  package.json
  src/distinct/README.md
  src/distinct/index.ts
  src/index.ts
  tests/index.test.ts
Labels: enhancement
